# .air.toml

root = "."
tmp_dir = "tmp"
build_dir = "bin"

[build]
  # Specify the entry point of your application
  # For example, if your main package is located at ./cmd/myapp/main.go, set:
  #   entry_point = "cmd/myapp"
  entry_point = "./main.go"

[web]
  port = "8080"

[[targets]]
  name = "app"
  src = "./..."
  cmd = "go run main.go"
